deployment:
  name: kibana
  replicaCount: 2
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: "7.6.0"
service:
  name: kibana
  svc:
    name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
configMap:
  name: kibana
global:
    namespace: monitoring
    svc:
        elasticsearch:
            name: elasticsearch
            port: 9200
        kibana:
            name: kibana
            port: 5601
