---
apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.service.name}}
  namespace: {{$.Values.global.namespace}}
  labels:
    app: {{$.Values.service.name}}
spec:
  selector:
    app: {{$.Values.service.name}}
  type: ClusterIP
  ports:
    {{- range $idx,$serv := $.Values.service.svc }}
    - port: {{ $serv.port }}
      name: {{ $serv.name }}
    {{- end }}
      
    
    