---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.configMap.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Values.configMap.name }}
data:
  kibana.yml: |-
    elasticsearch.hosts: "http://{{$.Values.global.svc.elasticsearch.name}}:{{$.Values.global.svc.elasticsearch.port}}"
    xpack.monitoring.enabled: true
    xpack.monitoring.kibana.collection.enabled: true
    server.host: "0.0.0.0"