apiVersion: v1
kind: Service
metadata:
  name: "{{$.Values.service.name}}-svc"
  namespace: {{$.Values.namespace}}
  labels:
    app: {{$.Values.service.name}}
spec:
  selector:
    app: {{$.Values.service.name}}
  ports:
  - port: {{$.Values.service.svc.port}}
    name: {{$.Values.service.svc.name}} 
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: "{{$.Values.service.name}}-lb"
  namespace: {{$.Values.namespace}}
  labels:                    
    app: {{$.Values.service.name}}
spec:                        
  type: LoadBalancer         
  selector:                  
    app: {{$.Values.service.name}}
  ports:                     
  - name: {{$.Values.service.svc.name}}               
    port: {{$.Values.service.svc.port}}
    targetPort: {{$.Values.service.svc.targetPort}}               
    protocol: {{$.Values.service.svc.protocol}}