---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  namespace: kube-system
  labels:
    k8s-app: {{ $.Values.app.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Values.clusterRole.name }}
  namespace: kube-system
  labels:
    k8s-app: {{ $.Values.app.name }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.app.name }}
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccount.name }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ $.Values.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io